[package]
name = "yiannis123git/smartraycast"
description = "RaycastParams management module for Roblox"
version = "1.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"


[dependencies]
Janitor = "howmanysmall/janitor@^1.15.4"
