[package]
name = "yiannis123git/smartraycast"
description = "Raycast Management Module for Efficient Raycasting"
version = "2.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"


[dependencies]
Janitor = "howmanysmall/janitor@^1.15.7"

